spring.application.name=backend
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/paf
spring.datasource.username=root
spring.datasource.password=

smartcampus.app.jwtSecret=smartcampus-super-secret-key-for-jwt-signing-minimum-256-bits-long
smartcampus.app.jwtExpirationMs=86400000

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

