spring.application.name=backend
server.port=8081

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:mysql://localhost:3306/smartCampus_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234

smartcampus.app.jwtSecret=${JWT_SECRET}
smartcampus.app.jwtExpirationMs=${JWT_EXPIRATION}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# File Upload Configuration
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB
app.file.upload-dir=uploads/resources

# Serve static resources from uploads directory
spring.web.resources.static-locations=file:${app.file.upload-dir}

